USE [master]
GO
/****** Object:  Database [LivroDataBase]    Script Date: 15/12/2024 10:16:41 ******/
CREATE DATABASE [LivroDataBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LivroDataBase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\LivroDataBase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LivroDataBase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\LivroDataBase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [LivroDataBase] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LivroDataBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LivroDataBase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LivroDataBase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LivroDataBase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LivroDataBase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LivroDataBase] SET ARITHABORT OFF 
GO
ALTER DATABASE [LivroDataBase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LivroDataBase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LivroDataBase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LivroDataBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LivroDataBase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LivroDataBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LivroDataBase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LivroDataBase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LivroDataBase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LivroDataBase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LivroDataBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LivroDataBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LivroDataBase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LivroDataBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LivroDataBase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LivroDataBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LivroDataBase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LivroDataBase] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LivroDataBase] SET  MULTI_USER 
GO
ALTER DATABASE [LivroDataBase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LivroDataBase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LivroDataBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LivroDataBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LivroDataBase] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LivroDataBase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [LivroDataBase] SET QUERY_STORE = OFF
GO
USE [LivroDataBase]
GO
/****** Object:  Table [dbo].[Cidades]    Script Date: 15/12/2024 10:16:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cidades](
	[idcidade] [bigint] IDENTITY(1,1) NOT NULL,
	[idestado] [bigint] NOT NULL,
	[nome] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Cidades] PRIMARY KEY CLUSTERED 
(
	[idcidade] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Estados]    Script Date: 15/12/2024 10:16:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estados](
	[idestado] [bigint] IDENTITY(1,1) NOT NULL,
	[uf] [nchar](2) NOT NULL,
	[nome] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Estados] PRIMARY KEY CLUSTERED 
(
	[idestado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Cidades]  WITH CHECK ADD  CONSTRAINT [FK_Cidades_Estados] FOREIGN KEY([idestado])
REFERENCES [dbo].[Estados] ([idestado])
GO
ALTER TABLE [dbo].[Cidades] CHECK CONSTRAINT [FK_Cidades_Estados]
GO
USE [master]
GO
ALTER DATABASE [LivroDataBase] SET  READ_WRITE 
GO
